### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by quickplot** [georgeto/Daffodil#1]
First of all this project and its concept is amazing, big thanks to everyone involved!  Being able to use all the compilers from the latest IDE is wonderful!
How is VS2017 Support?  Also is the project active?

**Comment by georgeto** [comment]
Just to clarify, I am not the author of the Daffodil project. I just forked the project, and improved the support of the v80 platform toolset (Visual Studio 2005).
Unless you are specifically interested in v80 I would recommend you to visit the [official project page](https://daffodil.codeplex.com/). There you will even find an installer.

> How is VS2017 Support?

VS 2017 support should at least okayish. I successfully compiled a v80 Project under VS 2017. But there is a [report](https://daffodil.codeplex.com/discussions/662237) which suggests that debugging could be a problem.

> Also is the project active?

It is not, the last commit in the official repository is from Oct 30, 2013.
