### ISSUE TITLE
VS2022 support

### ISSUE THREAD

**Issue by WHzhongyixin** [georgeto/Daffodil#3]
https://github.com/georgeto/Daffodil/blob/b036178e57aa5e16d61f455854276fe5f6e30d16/Platforms/Win32/v80/Microsoft.Cpp.Win32.v80.props#L22

The space before `</VCInstallDir>` make VS2022 compile VS2005 solution error.

**Comment by WHzhongyixin** [comment]
Error:
`<VCInstallDir Condition="'$(VCInstallDir)' == ''">$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\8.0\Setup\VC@ProductDir) </VCInstallDir>`

Corrected:
`<VCInstallDir Condition="'$(VCInstallDir)' == ''">$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\8.0\Setup\VC@ProductDir)</VCInstallDir>`

**Comment by georgeto** [comment]
Thanks for the report :)
